<?xml version="1.0"?>
<!-- Mobile Manipulation Robot -->
<robot name="momapbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants and/or parameters of robot -->
  <xacro:property name="PI" value="3.1415926535897931"/>

  <!-- Base -->
  <xacro:property name="base_width" value=".8"/>
  <xacro:property name="base_length" value="1"/>
  <xacro:property name="base_height" value=".25"/>
  <xacro:property name="base_mass" value="25"/>

  <!--Torso-->
  <xacro:property name="torso_width" value=".5"/>
  <xacro:property name="torso_length" value=".25"/>
  <xacro:property name="torso_height" value=".25"/>
  <xacro:property name="torso_mass" value="5"/>

  <!-- Wheels -->
  <xacro:property name="wheel_radius" value=".2"/>
  <xacro:property name="wheel_width" value=".1"/>
  <xacro:property name="wheel_mass" value="1"/>

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find momapbot_description)/urdf/momapbot.gazebo"/>

  <!-- Base -->
  <link name="base_link">

    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <!-- THIS INERTIA IS WRONG. IT IS MADE UP -->
      <inertia
	  ixx="${base_mass / 12.0 * (base_width*base_width + base_height*base_height)}" ixy="0.0" ixz="0.0"
	  iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
	  izz="${base_mass / 12.0 * (base_width*base_width + base_width*base_width)}"/>
    </inertial>

  </link>

  <!-- Torso -->
  <link name="torso">
    <visual>
      <geometry>
        <box size="${torso_length} ${torso_width} ${torso_height}"/>
      </geometry>
      <origin xyz="0 0 ${torso_height/2}"/>
      <material name="orange"/>
    </visual>

    <collision>
      <geometry>
        <box size="${torso_length} ${torso_width} ${torso_height}"/>
      </geometry>
      <origin xyz="0 0 ${torso_height/2}"/>
    </collision>

    <inertial>
      <origin xyz="0 0 ${torso_height/2}" rpy="0 0 0"/>
      <mass value="${torso_mass}"/>
      <!-- THIS INERTIA IS WRONG. IT IS MADE UP -->
      <inertia
	  ixx="${torso_mass / 12.0 * (torso_width*torso_width + torso_height*torso_height)}" ixy="0.0" ixz="0.0"
	  iyy="${torso_mass / 12.0 * (torso_height*torso_height + torso_width*torso_width)}" iyz="0.0"
	  izz="${torso_mass / 12.0 * (torso_width*torso_width + torso_width*torso_width)}"/>
    </inertial>

  </link>

  <joint name="base_to_torso" type="fixed">
    <parent link="base_link"/>
    <child link="torso"/>
    <origin xyz="0 0 ${base_height/2}"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${torso_height+.01}" rpy="0 0 0"/>
    <parent link="torso"/>
    <child link="hokuyo_link"/>
  </joint>


  <!-- Right Front Wheel -->
  <link name="right_front_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixy="0" ixz="0" iyz="0"
	       ixx="${wheel_mass/12 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
	       iyy="${wheel_mass/12 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
	       izz="${wheel_mass*wheel_radius*wheel_radius/2}"/>
    </inertial>

  </link>

  <!-- Left Front Wheel-->
  <link name="left_front_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixy="0" ixz="0" iyz="0"
	       ixx="${wheel_mass/12 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
	       iyy="${wheel_mass/12 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
	       izz="${wheel_mass*wheel_radius*wheel_radius/2}"/>
    </inertial>
  </link>

  <!-- Right Rear Wheel -->
  <link name="right_rear_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixy="0" ixz="0" iyz="0"
	       ixx="${wheel_mass/12 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
	       iyy="${wheel_mass/12 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
	       izz="${wheel_mass*wheel_radius*wheel_radius/2}"/>
    </inertial>


  </link>

  <!-- Left Rear Wheel -->
  <link name="left_rear_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixy="0" ixz="0" iyz="0"
	       ixx="${wheel_mass/12 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
	       iyy="${wheel_mass/12 * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
	       izz="${wheel_mass*wheel_radius*wheel_radius/2}"/>
    </inertial>
  </link>

  <joint name="base_to_right_front_wheel" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin rpy="${-PI/2} 0 0" xyz="${base_length/2-wheel_radius} ${-(base_width+wheel_width)/2-.01} 0.0"/>
  </joint>


  <transmission name="right_front_wheel_drive">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_right_front_wheel">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_front_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <joint name="base_to_left_front_wheel" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin rpy="${-PI/2} 0 0" xyz="${base_length/2-wheel_radius} ${(base_width+wheel_width)/2+.01} 0.0"/>
  </joint>


  <transmission name="left_front_wheel_drive">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_left_front_wheel">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_front_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <joint name="base_to_right_rear_wheel" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="right_rear_wheel"/>
    <origin rpy="${-PI/2} 0 0" xyz="${-(base_length/2-wheel_radius)} ${-(base_width+wheel_width)/2-.01} 0.0"/>
  </joint>

  <transmission name="right_rear_wheel_drive">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_right_rear_wheel">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_rear_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <joint name="base_to_left_rear_wheel" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="left_rear_wheel"/>
    <origin rpy="${-PI/2} 0 0" xyz="${-(base_length/2-wheel_radius)} ${(base_width+wheel_width)/2+.01} 0.0"/>
  </joint>

  <transmission name="left_rear_wheel_drive">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="base_to_left_rear_wheel">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_rear_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>



</robot>
