obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-1, -1], [-1, 1], [1, 1], [1, -1]]
inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo_frame, data_type: LaserScan, topic: scan2, marking: true, clearing: true}
